steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/simple-pimple', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/simple-pimple']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'evil'  # Replace with your Cloud Run service name
      - '--image'
      - 'us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/simple-pimple'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'  # Replace with your desired region
      - '--port'
      - '3000' # Replace with your desired region
      - '--set-env-vars'
      - 'SECRET_VERSION_NAME=projects/714859248413/secrets/harsh/versions/1'
      - '--allow-unauthenticated'

# Substitutions for variables, if needed
# substitutions:
#   _SERVICE_NAME: 'evil'
#   _REGION: 'us-central1'

# Optionally, define the Cloud Build trigger settings
options:
  logging: CLOUD_LOGGING_ONLY
  
images:
  - 'us-central1-docker.pkg.dev/gcp-training-710/gcf-artifacts/simple-pimple'
